const mongoose = require("mongoose");
const express = require("express");
const app = express();
const todoRouter = require("./routes/todoRouter.js");

app.use("/todos", todoRouter);

app.use(function (req, res){
    res.status(404).send("Not found");
});

mongoose.connect("mongodb+srv://mauzzz0:autogeneratedsecurepassword@cluster0.mr2pd.mongodb.net/myFirstDatabase?retryWrites=true&w=majority",
    { useUnifiedTopology: true, useNewUrlParser: true }, function(err){
    if(err) return console.log(err);
    app.listen(3000, function(){
        console.log("Сервер ожидает подключения...");
    });
});


