const mongoose = require("mongoose");
const express = require("express");
const app = express();
const todoRouter = require("./routes/todoRouter.js");
const { logger, errorHandler, asyncHandler, notFound, syncHandler} = require("./middlewares/middleware")
const { ErrorResponse } = require("./middlewares/ErrorResponse")
import fs from 'fs'
var a = 10
console.log('aa${a}aaa')
app.use(logger);

//app.use("/todos", todoRouter);


app.use(errorHandler);
app.use(notFound);

function readControllers() {
    const controllers = fs.readdirSync(__dirname + '/controllers/');

    for (let file of controllers) {
        const controller = require('${__dirname}')
    }
}

mongoose.connect("mongodb+srv://mauzzz0:autogeneratedsecurepassword@cluster0.mr2pd.mongodb.net/myFirstDatabase?retryWrites=true&w=majority",
    { useUnifiedTopology: true, useNewUrlParser: true }, function(err){
        if(err) return console.log(err);
        app.listen(3000, function(){
            console.log("Сервер ожидает подключения...");
        });
    });