import mongoose from 'mongoose'

mongoose.connect("mongodb+srv://mauzzz0:autogeneratedsecurepassword@cluster0.mr2pd.mongodb.net/myFirstDatabase?retryWrites=true&w=majority",
    { useUnifiedTopology: true, useNewUrlParser: true }, (err) => {
        if (err) return console.log(err);
        console.log('Connected to @cluster0.mr2pd.mongodb.net/myFirstDatabase?retryWrites=true&w=majority');
    });

