import mongoose from 'mongoose'

mongoose.connect("mongodb+srv://mauzzz0:autogeneratedsecurepassword@cluster0.mr2pd.mongodb.net/myFirstDatabase?retryWrites=true&w=majority",
    { useUnifiedTopology: true, useNewUrlParser: true}, () => {
        console.log('Connected to @cluster0.mr2pd.mongodb.net/myFirstDatabase?retryWrites=true&w=majority');
    });

